//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long appointmentId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> startTime { get; set; }
        public Nullable<int> endTime { get; set; }
        public Nullable<long> patientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
